# version: '3.1'
# services:
#   db:
#     image: postgres:latest
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: banking_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data 
# volumes:
#   pgdata: 
